- name: Create an EC2 Instance
  hosts: localhost
  tasks:
    - name: Create an ec2
      ec2:
        exact_count: 1
        key_name: devops
        instance_type: t3.micro
        image: ami-06553e40eb432837c
        region: us-east-1
        wait: true
        group_id: sg-0c8c47788cfcac54e
        instance_profile_name: D47-RoboShop-EC2-Instance-Role
        instance_tags:
          Name: "{{item}}"
        count_tag: "{{item}}"
      register: ec2
      loop:
        - cart


    - name: debug
      debug:
        msg: "{{ item.instances[0] }}"
      loop: "{{ec2.results}}"

#    - name: Add cart instance to host group
#      add_host:
#        hostname: "{{ item.instances[0].public_ip }}"
#        groupname: cart
#      loop: "{{ec2.results[0]}}"
#
#    - name: Add catalogue instance to host group
#      add_host:
#        hostname: "{{ item.instances[0].public_ip }}"
#        groupname: catalogue
#      loop: "{{ec2.results[1]}}"

#    - name: Wait for SSH to come up
#      delegate_to: "{{ item.public_dns_name }}"
#      wait_for_connection:
#        delay: 60
#        timeout: 320
#      loop: "{{ ec2.instances }}"


- name: Configure instance(s) cart
  hosts: cart
  become: True
  gather_facts: True
  tasks:
    - name: Say Hello
      debug:
        msg: "{{anisble_fqdn}}"

- name: Configure instance(s) catalogue
  hosts: catalogue
  become: True
  gather_facts: True
  tasks:
    - name: Say Hello
      debug:
        msg: "{{anisble_fqdn}}"
