- name: Deploy
  hosts: all
  become: yes
  serial: 1
  tasks:
    - name: Install Nginx
      package:
        name: nginx
        state: installed

    - name: Start nginx
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Deployment
      copy:
        src: index.html
        dest: /usr/share/nginx/html/index.html
